package db

import (
	price_analyzer_api "price_analyzer_prototype/api"
	"time"
)

type Product struct {
	tableName struct{} `pg:"product,alias:t,discard_unknown_columns"`

	ID         string     `pg:"id,pk,type:int" db:"id"`
	Name       *string    `pg:"name" db:"name"`
	Code       string     `pg:"code,use_zero" db:"code"`
	UpdatedAt  *time.Time `pg:"updated_at" db:"updated_at"`
	CategoryID *int       `pg:"category_id" db:"category_id"`
	IsActive   bool       `pg:"is_active,use_zero" db:"is_active"`

	//Brand       *Brand       `pg:"fk:brand_id"`
	Category *Category `pg:"fk:category_id"`
}

// TODO: toAPI in other package. This folder for autogenerated db-structs
func (p *Product) ToProductAPI() *price_analyzer_api.Product {
	return &price_analyzer_api.Product{
		Id:   p.ID,
		Name: *p.Name,
	}
}
