// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/price_analyze.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductListRequest struct {
	// Types that are valid to be assigned to CategoryId:
	//	*ProductListRequest_Id
	//	*ProductListRequest_OldId
	CategoryId           isProductListRequest_CategoryId `protobuf_oneof:"category_id"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ProductListRequest) Reset()         { *m = ProductListRequest{} }
func (m *ProductListRequest) String() string { return proto.CompactTextString(m) }
func (*ProductListRequest) ProtoMessage()    {}
func (*ProductListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{0}
}

func (m *ProductListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductListRequest.Unmarshal(m, b)
}
func (m *ProductListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductListRequest.Marshal(b, m, deterministic)
}
func (m *ProductListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductListRequest.Merge(m, src)
}
func (m *ProductListRequest) XXX_Size() int {
	return xxx_messageInfo_ProductListRequest.Size(m)
}
func (m *ProductListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductListRequest proto.InternalMessageInfo

type isProductListRequest_CategoryId interface {
	isProductListRequest_CategoryId()
}

type ProductListRequest_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type ProductListRequest_OldId struct {
	OldId int32 `protobuf:"varint,2,opt,name=old_id,json=oldId,proto3,oneof"`
}

func (*ProductListRequest_Id) isProductListRequest_CategoryId() {}

func (*ProductListRequest_OldId) isProductListRequest_CategoryId() {}

func (m *ProductListRequest) GetCategoryId() isProductListRequest_CategoryId {
	if m != nil {
		return m.CategoryId
	}
	return nil
}

func (m *ProductListRequest) GetId() int32 {
	if x, ok := m.GetCategoryId().(*ProductListRequest_Id); ok {
		return x.Id
	}
	return 0
}

func (m *ProductListRequest) GetOldId() int32 {
	if x, ok := m.GetCategoryId().(*ProductListRequest_OldId); ok {
		return x.OldId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProductListRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProductListRequest_Id)(nil),
		(*ProductListRequest_OldId)(nil),
	}
}

type Product struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// название
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// информация о бренде
	//  ProductBrand brand = 3;*/
	//  // информация о производителе
	//  ProductProducer producer = 4;
	//  // описания
	//  ProductInstruction instruction = 5;
	//  // символьный код (ссылка)
	//  string code = 6;
	//  // дата создания
	//  google.protobuf.Timestamp created_at = 7;
	//  // дата изменения
	//  google.protobuf.Timestamp updated_at = 8;
	//  // краткое описание
	//  string short_desc = 9;
	// атрибуты в формате code => свойство
	//  map<string, ProductAttribute> attributes = 10;
	// ссылка
	Url                  string   `protobuf:"bytes,12,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ProductListResponse struct {
	// товары
	Items                []*Product `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductListResponse) Reset()         { *m = ProductListResponse{} }
func (m *ProductListResponse) String() string { return proto.CompactTextString(m) }
func (*ProductListResponse) ProtoMessage()    {}
func (*ProductListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{2}
}

func (m *ProductListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductListResponse.Unmarshal(m, b)
}
func (m *ProductListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductListResponse.Marshal(b, m, deterministic)
}
func (m *ProductListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductListResponse.Merge(m, src)
}
func (m *ProductListResponse) XXX_Size() int {
	return xxx_messageInfo_ProductListResponse.Size(m)
}
func (m *ProductListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductListResponse proto.InternalMessageInfo

func (m *ProductListResponse) GetItems() []*Product {
	if m != nil {
		return m.Items
	}
	return nil
}

type CategoryListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryListRequest) Reset()         { *m = CategoryListRequest{} }
func (m *CategoryListRequest) String() string { return proto.CompactTextString(m) }
func (*CategoryListRequest) ProtoMessage()    {}
func (*CategoryListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{3}
}

func (m *CategoryListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryListRequest.Unmarshal(m, b)
}
func (m *CategoryListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryListRequest.Marshal(b, m, deterministic)
}
func (m *CategoryListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryListRequest.Merge(m, src)
}
func (m *CategoryListRequest) XXX_Size() int {
	return xxx_messageInfo_CategoryListRequest.Size(m)
}
func (m *CategoryListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryListRequest proto.InternalMessageInfo

type Category struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{4}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CategoryListResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryListResponse) Reset()         { *m = CategoryListResponse{} }
func (m *CategoryListResponse) String() string { return proto.CompactTextString(m) }
func (*CategoryListResponse) ProtoMessage()    {}
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{5}
}

func (m *CategoryListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryListResponse.Unmarshal(m, b)
}
func (m *CategoryListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryListResponse.Marshal(b, m, deterministic)
}
func (m *CategoryListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryListResponse.Merge(m, src)
}
func (m *CategoryListResponse) XXX_Size() int {
	return xxx_messageInfo_CategoryListResponse.Size(m)
}
func (m *CategoryListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryListResponse proto.InternalMessageInfo

type GetProductsFilterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsFilterRequest) Reset()         { *m = GetProductsFilterRequest{} }
func (m *GetProductsFilterRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsFilterRequest) ProtoMessage()    {}
func (*GetProductsFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{6}
}

func (m *GetProductsFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsFilterRequest.Unmarshal(m, b)
}
func (m *GetProductsFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsFilterRequest.Marshal(b, m, deterministic)
}
func (m *GetProductsFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsFilterRequest.Merge(m, src)
}
func (m *GetProductsFilterRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsFilterRequest.Size(m)
}
func (m *GetProductsFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsFilterRequest proto.InternalMessageInfo

type GetProductsFilterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsFilterResponse) Reset()         { *m = GetProductsFilterResponse{} }
func (m *GetProductsFilterResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsFilterResponse) ProtoMessage()    {}
func (*GetProductsFilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{7}
}

func (m *GetProductsFilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsFilterResponse.Unmarshal(m, b)
}
func (m *GetProductsFilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsFilterResponse.Marshal(b, m, deterministic)
}
func (m *GetProductsFilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsFilterResponse.Merge(m, src)
}
func (m *GetProductsFilterResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsFilterResponse.Size(m)
}
func (m *GetProductsFilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsFilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsFilterResponse proto.InternalMessageInfo

type AddProductsFilterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductsFilterRequest) Reset()         { *m = AddProductsFilterRequest{} }
func (m *AddProductsFilterRequest) String() string { return proto.CompactTextString(m) }
func (*AddProductsFilterRequest) ProtoMessage()    {}
func (*AddProductsFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{8}
}

func (m *AddProductsFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductsFilterRequest.Unmarshal(m, b)
}
func (m *AddProductsFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductsFilterRequest.Marshal(b, m, deterministic)
}
func (m *AddProductsFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductsFilterRequest.Merge(m, src)
}
func (m *AddProductsFilterRequest) XXX_Size() int {
	return xxx_messageInfo_AddProductsFilterRequest.Size(m)
}
func (m *AddProductsFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductsFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductsFilterRequest proto.InternalMessageInfo

type AddProductsFilterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductsFilterResponse) Reset()         { *m = AddProductsFilterResponse{} }
func (m *AddProductsFilterResponse) String() string { return proto.CompactTextString(m) }
func (*AddProductsFilterResponse) ProtoMessage()    {}
func (*AddProductsFilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5088d214c39ec58e, []int{9}
}

func (m *AddProductsFilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductsFilterResponse.Unmarshal(m, b)
}
func (m *AddProductsFilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductsFilterResponse.Marshal(b, m, deterministic)
}
func (m *AddProductsFilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductsFilterResponse.Merge(m, src)
}
func (m *AddProductsFilterResponse) XXX_Size() int {
	return xxx_messageInfo_AddProductsFilterResponse.Size(m)
}
func (m *AddProductsFilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductsFilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductsFilterResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProductListRequest)(nil), "api.ProductListRequest")
	proto.RegisterType((*Product)(nil), "api.Product")
	proto.RegisterType((*ProductListResponse)(nil), "api.ProductListResponse")
	proto.RegisterType((*CategoryListRequest)(nil), "api.CategoryListRequest")
	proto.RegisterType((*Category)(nil), "api.Category")
	proto.RegisterType((*CategoryListResponse)(nil), "api.CategoryListResponse")
	proto.RegisterType((*GetProductsFilterRequest)(nil), "api.GetProductsFilterRequest")
	proto.RegisterType((*GetProductsFilterResponse)(nil), "api.GetProductsFilterResponse")
	proto.RegisterType((*AddProductsFilterRequest)(nil), "api.AddProductsFilterRequest")
	proto.RegisterType((*AddProductsFilterResponse)(nil), "api.AddProductsFilterResponse")
}

func init() { proto.RegisterFile("api/price_analyze.proto", fileDescriptor_5088d214c39ec58e) }

var fileDescriptor_5088d214c39ec58e = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x49, 0x42, 0xc7, 0x76, 0x56, 0xb6, 0xee, 0x6c, 0x90, 0x2c, 0x88, 0x69, 0xf8, 0x6a,
	0x57, 0xad, 0x18, 0x57, 0x88, 0x0b, 0xb4, 0x21, 0x31, 0x90, 0x10, 0x9a, 0x72, 0x89, 0x84, 0x22,
	0xb7, 0x36, 0x60, 0x91, 0xc6, 0xc6, 0x76, 0x91, 0xca, 0x25, 0xaf, 0xc0, 0x63, 0xf0, 0x38, 0xbc,
	0x02, 0x0f, 0x82, 0xe2, 0x38, 0x6d, 0x4a, 0x93, 0xbb, 0xe8, 0x7c, 0xe7, 0x7c, 0xbf, 0xf3, 0xc7,
	0x81, 0x98, 0x2a, 0x31, 0x51, 0x5a, 0xcc, 0x78, 0x4e, 0x4b, 0x5a, 0x2c, 0x7f, 0xf0, 0xb1, 0xd2,
	0xd2, 0x4a, 0x8c, 0xa8, 0x12, 0xe9, 0x13, 0xfb, 0x45, 0x68, 0x96, 0x2b, 0xaa, 0xed, 0x72, 0x52,
	0x65, 0xd2, 0xb2, 0x94, 0x96, 0x5a, 0x21, 0x4b, 0x53, 0xe7, 0x91, 0xf7, 0x80, 0xb7, 0x5a, 0xb2,
	0xc5, 0xcc, 0xbe, 0x13, 0xc6, 0x66, 0xfc, 0xdb, 0x82, 0x1b, 0x8b, 0x23, 0x08, 0x05, 0x4b, 0x82,
	0xf3, 0xe0, 0x62, 0xf0, 0xe6, 0x4e, 0x16, 0x0a, 0x86, 0x31, 0xec, 0xc8, 0x82, 0xe5, 0x82, 0x25,
	0xa1, 0x8f, 0x0e, 0x64, 0xc1, 0xde, 0xb2, 0xeb, 0xfb, 0xb0, 0x3f, 0xa3, 0x96, 0x7f, 0x96, 0x7a,
	0x99, 0x0b, 0x46, 0x5e, 0xc2, 0x3d, 0xef, 0x87, 0x07, 0x2b, 0x93, 0x3d, 0x67, 0x81, 0x70, 0xb7,
	0xa4, 0x73, 0xee, 0x0c, 0xf6, 0x32, 0xf7, 0x8d, 0x23, 0x88, 0x16, 0xba, 0x48, 0x86, 0x2e, 0x54,
	0x7d, 0x92, 0xe7, 0x70, 0xbc, 0xd1, 0x90, 0x51, 0xb2, 0x34, 0x1c, 0x09, 0x0c, 0x84, 0xe5, 0x73,
	0x93, 0x04, 0xe7, 0xd1, 0xc5, 0xfe, 0xe5, 0x70, 0x4c, 0x95, 0x18, 0xfb, 0xc4, 0xac, 0x96, 0xc8,
	0x03, 0x38, 0x7e, 0xe5, 0x5b, 0x69, 0x0d, 0x43, 0xce, 0x60, 0xb7, 0x09, 0xaf, 0x7a, 0x08, 0xd6,
	0x3d, 0x90, 0x87, 0x70, 0xb2, 0x59, 0x56, 0x23, 0x49, 0x0a, 0xc9, 0x0d, 0xb7, 0x9e, 0x61, 0x5e,
	0x8b, 0xc2, 0x72, 0xdd, 0x78, 0x3e, 0x82, 0xd3, 0x0e, 0x6d, 0x5d, 0x78, 0xc5, 0x58, 0x6f, 0x61,
	0x87, 0x56, 0x17, 0x5e, 0xfe, 0x8e, 0x60, 0x78, 0x5b, 0x1d, 0xf3, 0xaa, 0xbe, 0x25, 0x7e, 0x84,
	0x83, 0x35, 0xa6, 0x6a, 0x0e, 0xe3, 0xf6, 0xe0, 0xad, 0x29, 0xd3, 0x64, 0x5b, 0xf0, 0xed, 0x24,
	0x3f, 0xff, 0xfc, 0xfd, 0x15, 0x22, 0x8e, 0xdc, 0x13, 0xf8, 0xfe, 0x74, 0xa2, 0x3c, 0x1d, 0xa7,
	0x70, 0x78, 0xc3, 0x6d, 0x7b, 0x78, 0xac, 0x6d, 0x3a, 0xd6, 0x98, 0x9e, 0x76, 0x28, 0xcd, 0xc0,
	0x8e, 0x70, 0x82, 0xd8, 0x10, 0xfc, 0x8b, 0x10, 0xdc, 0xe0, 0x57, 0x38, 0xda, 0xda, 0x14, 0x3e,
	0x76, 0x5e, 0x7d, 0xdb, 0x4d, 0xcf, 0xfa, 0x64, 0xcf, 0x8b, 0x1d, 0xef, 0x08, 0x0f, 0x1b, 0xde,
	0x27, 0xa7, 0x3b, 0xd8, 0xd6, 0x76, 0x3d, 0xac, 0xef, 0x22, 0x1e, 0xd6, 0x7b, 0x94, 0x06, 0x46,
	0xfe, 0x87, 0x5d, 0xc3, 0x87, 0xdd, 0x2a, 0xf4, 0x82, 0x2a, 0x31, 0xdd, 0x71, 0x7f, 0xd3, 0xb3,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x1f, 0x14, 0xad, 0x90, 0x03, 0x00, 0x00,
}
